[package]
name = "llmagent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
rig-core = { version = "0.37.0", features = ["rmcp"] }
tokio = { version = "1.52.1", features = ["full"] }
serde_json = "1"
serde = "1"
rmcp = { version = "1.6.0", features = ["server", "macros", "client", "transport-io", "transport-streamable-http-server", "transport-streamable-http-client-unix-socket", "transport-streamable-http-client-reqwest"] }
axum = "0.8.9"
tokio-util = { version = "0.7", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "fmt",
] }

tower-http = {version = "0.6.10", features = ["cors",]}
hyper-util = "0.1.20"
thiserror = "2.0.18"
chinese-number = {version = "0.7.8", features = ["number-to-chinese", "chinese-to-number"]}
